spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blog_backend_db
    username: postgres
    password: 0123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
